### PR TITLE
Fix git clone issues for DscResource.Tests - Fixes #287

### LINKED ISSUE #287: Unable to run Git Clone with apostrophe in the Directory Path
While attempting to run pester to test my new module against the DSC Resource tests I encountered an error while running the git clone command.  

git.exe : fatal: could not create work tree dir 'C:\Users\USERNAME\OneDrive - D'Arcy\Source\Repos\LanguageDsc\DSCResource.Tests"': Invalid argument

I believe that it is to do with the apostrophe within my name, is there a way to delimit this as replacing with %27, '', `' and \' haven't worked

### PR DESCRIPTION
**Pull request by ld0614**
Remove the trailing backslash from the git clone within the DSC Testing templates.  This caused an issue when the file path had an apostrophe in it.  See Issue #287

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/299)

### CODE REVIEW

**Comment by johlju** [comment]
@ld0614 Can you please change the PR title to 'Fix git clone issues for DscResource.Tests - Fixes #287'

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpkcirA5KNb2XR6--Tf:-KpkcirA5KNb2XR6--Tg:b7wyaj7) ([raw file](https://github.com/powershell/dscresources/blob/81b00ef13b9f3ca38b531ae06d6530a919f5982a/Tests.Template/integration_template.ps1#L25)):*
> '\DSCResource.Tests'

Please remove the first '\' as well.

---

*[Tests.Template/unit_template.ps1, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpkcqSK6NSw8WN33Bhy:-KpkcqSK6NSw8WN33Bhz:b6fmxdq) ([raw file](https://github.com/powershell/dscresources/blob/81b00ef13b9f3ca38b531ae06d6530a919f5982a/Tests.Template/unit_template.ps1#L24)):*
> '\DSCResource.Tests

Please remove the first '\' as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299#-:-KpkcSaXDUG2CB8fTDIy:b-s02cex)*

**Comment by johlju** [comment]
@ld0614 Thanks for sending in a PR to fix this!

When you fixed these review comments, then please go into Reviewable and write 'Done' or click the Done-button on each comment (if you want to discuss a review comment, then don't write 'Done'). When you have answered all review comment, then you click the big green Publish-button at the top of the Reviewable page, that will send all comments back here to GitHub.
You find Reviewable at the top of the the PR, the big purple button in the PR description. 😄

**Comment by johlju** [comment]
Saw that markdown removed the backslash.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpkcirA5KNb2XR6--Tf:-Kpke0C8dTuyE6Ej5B5t:b-ti6dlt) ([raw file](https://github.com/powershell/dscresources/blob/81b00ef13b9f3ca38b531ae06d6530a919f5982a/Tests.Template/integration_template.ps1#L25)):*
> '\DSCResource.Tests'

Please remove the first '\\' as well.

---

*[Tests.Template/unit_template.ps1, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpkcqSK6NSw8WN33Bhy:-Kpke5CCShW9sdknAsCP:b-ti6dlt) ([raw file](https://github.com/powershell/dscresources/blob/81b00ef13b9f3ca38b531ae06d6530a919f5982a/Tests.Template/unit_template.ps1#L24)):*
> '\DSCResource.Tests'

Please remove the first '\\' as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299#-:-KpkeCpw9UibpF_zzAlp:bbljxqz)*

**Comment by ld0614** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 25 at r1](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpkcirA5KNb2XR6--Tf:-Kpkn45jxOjv5HLoWNc-:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/81b00ef13b9f3ca38b531ae06d6530a919f5982a/Tests.Template/integration_template.ps1#L25)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> '\DSCResource.Tests'

Please remove the first '\\' as well.
</blockquote></details>

Done.

---

*[Tests.Template/unit_template.ps1, line 24 at r1](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpkcqSK6NSw8WN33Bhy:-Kpkn7nqdWL4i3ydDpYF:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/81b00ef13b9f3ca38b531ae06d6530a919f5982a/Tests.Template/unit_template.ps1#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> '\DSCResource.Tests'

Please remove the first '\\' as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299#-:-Kpl-8PW9hmN_PAZtzjI:bnfp4nl)*

**Comment by johlju** [comment]
@mbreakey3 or @kwirkykat can you look thru this when ever you have a chance?

**Comment by johlju** [comment]
@ld0614 I found a minor typo in the comment-based help section (when I was about to use the template just now). Would you mind fixing that also?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Tests.Template/integration_template.ps1, line 6 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo1-GbqqvmSN-ROaeF:-Kpo1-GbqqvmSN-ROaeG:b-yqej8t) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L6)):*
> xNeworking

Should be xNetworking

---

*[Tests.Template/integration_template.ps1, line 8 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo14IPmA9Ayy5Dx0pj:-Kpo14IPmA9Ayy5Dx0pk:b-yqej8t) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L8)):*
> xNeworking

Should be xNetworking

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299#-:-Kpo19BRIS7_AbaF7FNm:b-nb4zvh)*

**Comment by johlju** [comment]
@ld0614 I saw now there is a changelist.md here https://github.com/PowerShell/DscResources/blob/master/Tests.Template/changelist.md. Could you please update that as well?

I didn't know about this file. I see also that the previous changes for the unit template has not been updated for a while. :/ But please update your changes in that file.

**Comment by johlju** [comment]
I found some more typos. Would you mind fixing these so they align to the style guideline more?

Sorry for making so much comments on code that you have not changed, but it would be awesome if you could help fix these as well. :smile: 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 50 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo6ur9XQ0ggtYspXhe:-Kpo6ur9XQ0ggtYspXhf:bk0mx1q) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L50)):*
> ```PowerShell
>             {
>                 & "$($script:DSCResourceName)_Config" -OutputPath $TestDrive
>                 Start-DscConfiguration -Path $TestDrive `
> ```

Blank row before this one

---

*[Tests.Template/integration_template.ps1, line 52 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo71pbGS0jQlcAJEcj:-Kpo71pbGS0jQlcAJEck:b-j1nybf) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L52)):*
> not throw

Not Throw (upper 'N' and 'T')

---

*[Tests.Template/integration_template.ps1, line 56 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo6xzmn88Pc0Si0WSw:-Kpo6xzmn88Pc0Si0WSx:b-1f09b8) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L56)):*
> Not throw

Not Throw (upper 'T')

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299#-:-Kpo7LZxytThmFj36fBw:b-w5v8aw)*

**Comment by ld0614** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[StyleGuidelines.md, line 169 at r3](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpoStDwuD1272ja8y8A:-KpoStDwuD1272ja8y8B:b-gzg9qk) ([raw file](https://github.com/powershell/dscresources/blob/38a21d4230add285dbd903104f1e33e2290e7e26/StyleGuidelines.md#L169)):*
> ```Markdown
> 
> Arrays should be written in the following format.
> Arrays should be written on one line unless they exceed the line character limit.
> ```

Added minor spelling correction

---

*[StyleGuidelines.md, line 237 at r3](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpoSx-S18H0-qus9mkZ:-KpoSx-S18H0-qus9mk_:b-gzg9qk) ([raw file](https://github.com/powershell/dscresources/blob/38a21d4230add285dbd903104f1e33e2290e7e26/StyleGuidelines.md#L237)):*
> ```Markdown
> 
> There should not be any commented-out code in checked-in files.
> The first letter of the comment should be capitalized.
> ```

Added minor spelling correction

---

*[StyleGuidelines.md, line 808 at r3](https://reviewable.io:443/reviews/powershell/dscresources/299#-KpoSxoxsy8y8VV5HZLp:-KpoSxoxsy8y8VV5HZLq:b-gzg9qk) ([raw file](https://github.com/powershell/dscresources/blob/38a21d4230add285dbd903104f1e33e2290e7e26/StyleGuidelines.md#L808)):*
> ```Markdown
> ### Parameter Block at Top of Function
> 
> There must be a parameter block declared for every function.
> ```

Added minor spelling correction

---

*[Tests.Template/integration_template.ps1, line 6 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo1-GbqqvmSN-ROaeF:-KpoSQbTLS7cal7x24-d:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> xNeworking

Should be xNetworking
</blockquote></details>

Done.

---

*[Tests.Template/integration_template.ps1, line 8 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo14IPmA9Ayy5Dx0pj:-KpoSRC5SDTDbcn_3rVf:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> xNeworking

Should be xNetworking
</blockquote></details>

Done.

---

*[Tests.Template/integration_template.ps1, line 50 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo6ur9XQ0ggtYspXhe:-KpoSTCjRYG8GQVVnLM3:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L50)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank row before this one
</blockquote></details>

Done.

---

*[Tests.Template/integration_template.ps1, line 52 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo71pbGS0jQlcAJEcj:-KpoSbucxvrbXU7XNNAc:b-dvzo82) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L52)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> not throw

Not Throw (upper 'N' and 'T')
</blockquote></details>

Done but I can't see a reference within the style guidelines, am I missing it or should it be added?

---

*[Tests.Template/integration_template.ps1, line 56 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo6xzmn88Pc0Si0WSw:-KpoSnU9LhEolS9d2tTc:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L56)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Not throw

Not Throw (upper 'T')
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299)*

**Comment by ld0614** [comment]
I'm quite happy to help fix things as I go along, I also added some fixes for the style guidelines, not sure if they should be moved to a separate pull request though?

**Comment by johlju** [comment]
:lgtm:

Nah, I think this can be in the PR. Thanks for fixing those. Now I shall try not to comment on anything else so you can get this merge. Looking good to me.

You will have to wait until @mbreakey3 or @kwirkykat have time to come around and review this also, and then they will merge.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests.Template/integration_template.ps1, line 52 at r2](https://reviewable.io:443/reviews/powershell/dscresources/299#-Kpo71pbGS0jQlcAJEcj:-KpoY7P0hiKDbx_S61HX:b-ro6e2) ([raw file](https://github.com/powershell/dscresources/blob/ed4bce08d2b375138705664a7d6e0006fe94f09f/Tests.Template/integration_template.ps1#L52)):*
<details><summary><i>Previously, ld0614 wrote…</i></summary><blockquote>

Done but I can't see a reference within the style guidelines, am I missing it or should it be added?
</blockquote></details>

I opened issue #300 so we can make sure to update the test guideline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/299#-:-KpoYCluFOqIApODhgg8:bosn8y8)*

**Pull request merged**
