### PR TITLE
Fix submodule encodings

### PR DESCRIPTION
**Pull request by Iristyle**

### CODE REVIEW

**Comment by Iristyle** [comment]
We're also looking for https://github.com/PowerShell/xExchange/pull/22/files and https://github.com/PowerShell/xStorage/pull/6/files to be merged ... and I will throw the 2 additional commits to bump the subrepos for those as well.

**Comment by KarolKaczmarek** [comment]
merged two PRs mentioned about. I'll wait for commits for them here as well before merging.

**Comment by Iristyle** [comment]
@KarolKaczmarek this PR is all set now - thanks for the quick response!

**Comment by KarolKaczmarek** [comment]
Thanks!

**Comment by ferventcoder** [comment]
Thank you!

**Pull request merged**
