### PR TITLE
Added documentation helper module

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Related to discussion #167 

This additional module can be used to generate documentation for DSC resources.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/171)

### CODE REVIEW

**Comment by KarolKaczmarek** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[DscResource.DocumentationHelper/Modules/MofHelper.psm1, line 1 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KOMRMybjm1t3hMBDYIq:-KOMRMybjm1t3hMBDYIr:786003473) ([raw file](https://github.com/powershell/dscresources/blob/d016feeeb7543f7498269bd2324315bcd33db3a3/DscResource.DocumentationHelper/Modules/MofHelper.psm1#L1)):*
> ```PowerShell
> function Get-MofSchemaObject() 
> ```

Please add comment based help to all exported functions

---

*[DscResource.DocumentationHelper/Modules/MofHelper.psm1, line 28 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KOMPEwQRlAnKbvaAlgG:-KOMPEwReaKQlj7D5API:-1942222464) ([raw file](https://github.com/powershell/dscresources/blob/d016feeeb7543f7498269bd2324315bcd33db3a3/DscResource.DocumentationHelper/Modules/MofHelper.psm1#L28)):*
> ```PowerShell
>             $currentlyInCommentBlock = $true
>         } 
>         elseif($textLine.StartsWith("*/")) 
> ```

What about */ on the other places, e.g. after some (white) characters/at the end of the line?

If we require some very specific format, could you document it? I think we should also have some sort of validation the mof file has the expected format.

Some readme.md with information about this module would be helpful as well

---

*[DscResource.DocumentationHelper/Modules/PowerShellHelp.psm1, line 21 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KOMSqWkknkN4FPmb4xw:-KOMSqWlBvLwyBCar1Hh:858755710) ([raw file](https://github.com/powershell/dscresources/blob/d016feeeb7543f7498269bd2324315bcd33db3a3/DscResource.DocumentationHelper/Modules/PowerShellHelp.psm1#L21)):*
> ```PowerShell
>         $mofFileObject = $_ 
> 
>         $descriptionPath = Join-Path -Path $_.DirectoryName -ChildPath "readme.md"
> ```

Is it the module you are using currently for SharepointDsc? I don't see those description readme.md files there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/171)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[DscResource.DocumentationHelper/Modules/MofHelper.psm1, line 1 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KOMRMybjm1t3hMBDYIq:-KOcDM_pvaJoFJAqzioE:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/d016feeeb7543f7498269bd2324315bcd33db3a3/DscResource.DocumentationHelper/Modules/MofHelper.psm1#L1)):*
<details><summary><i>Previously, KarolKaczmarek (Karol Kaczmarek) wrote…</i></summary>
> Please add comment based help to all exported functions
</details>
Done.

---

*[DscResource.DocumentationHelper/Modules/MofHelper.psm1, line 28 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KOMPEwQRlAnKbvaAlgG:-KOcDNeCQ-DFU2y7QaD0:b-tn0pso) ([raw file](https://github.com/powershell/dscresources/blob/d016feeeb7543f7498269bd2324315bcd33db3a3/DscResource.DocumentationHelper/Modules/MofHelper.psm1#L28)):*
<details><summary><i>Previously, KarolKaczmarek (Karol Kaczmarek) wrote…</i></summary>
> What about */ on the other places, e.g. after some (white) characters/at the end of the line?
> 
> If we require some very specific format, could you document it? I think we should also have some sort of validation the mof file has the expected format.
> 
> Some readme.md with information about this module would be helpful as well
</details>
This was a hang over from how we used to do the documentation in SharePoint DSC so should be removed, so I'll review but probably remove.

The readme file is a good idea, so I can put that together. Will advise here when its done

---

*[DscResource.DocumentationHelper/Modules/PowerShellHelp.psm1, line 21 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KOMSqWkknkN4FPmb4xw:-KOcDgobbLfl0ulMEhto:b-3croag) ([raw file](https://github.com/powershell/dscresources/blob/d016feeeb7543f7498269bd2324315bcd33db3a3/DscResource.DocumentationHelper/Modules/PowerShellHelp.psm1#L21)):*
<details><summary><i>Previously, KarolKaczmarek (Karol Kaczmarek) wrote…</i></summary>
> Is it the module you are using currently for SharepointDsc? I don't see those description readme.md files there
</details>
It was in a pull request waiting on review - the PR has been merged down so you can see them in the dev branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/171)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[DscResource.DocumentationHelper/Modules/MofHelper.psm1, line 28 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KOMPEwQRlAnKbvaAlgG:-KOcMb0Rz4QqKNYoQzqT:b-g2iv2f) ([raw file](https://github.com/powershell/dscresources/blob/d016feeeb7543f7498269bd2324315bcd33db3a3/DscResource.DocumentationHelper/Modules/MofHelper.psm1#L28)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> This was a hang over from how we used to do the documentation in SharePoint DSC so should be removed, so I'll review but probably remove.
> 
> The readme file is a good idea, so I can put that together. Will advise here when its done
</details>
Cleaned up this specific bit and just let it ignore comment lines, and I added the readme file with the examples of the output, let me know what you think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/171)*

**Comment by KarolKaczmarek** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[DscResource.DocumentationHelper/DscResource.DocumentationHelper.psd1, line 74 \[r2\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KPtlrZ3rsOr9y_jsrxC:-KPtlrZ3rsOr9y_jsrxD:b-ngd36a) ([raw file](https://github.com/powershell/dscresources/blob/8468c931ddfc91a273bdd015e90826ba4f6a9e99/DscResource.DocumentationHelper/DscResource.DocumentationHelper.psd1#L74)):*
> ```PowerShell
> 
> # Cmdlets to export from this module
> CmdletsToExport = @("Get-MofSchemaObject",
> ```

Is there scenario where we would call Get-MofSchemaObject directly or can we make it private to avoid confusion?

---

*[DscResource.DocumentationHelper/readme.md, line 24 \[r2\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KPtkOzSegc7QKn62v5v:-KPtkOzSegc7QKn62v5w:b-j59eww) ([raw file](https://github.com/powershell/dscresources/blob/8468c931ddfc91a273bdd015e90826ba4f6a9e99/DscResource.DocumentationHelper/readme.md#L24)):*
> p this specific bit and just let it ignore comment lines, and I a
typo: resource

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/171)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[DscResource.DocumentationHelper/DscResource.DocumentationHelper.psd1, line 74 \[r2\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KPtlrZ3rsOr9y_jsrxC:-KQNh0lpfKR0e1agtH8L:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/8468c931ddfc91a273bdd015e90826ba4f6a9e99/DscResource.DocumentationHelper/DscResource.DocumentationHelper.psd1#L74)):*
<details><summary><i>Previously, KarolKaczmarek (Karol Kaczmarek) wrote…</i></summary>
> Is there scenario where we would call Get-MofSchemaObject directly or can we make it private to avoid confusion?
</details>
Done.

---

*[DscResource.DocumentationHelper/readme.md, line 24 \[r2\]](https://reviewable.io:443/reviews/powershell/dscresources/171#-KPtkOzSegc7QKn62v5v:-KQNh2uC9D4iu52eEC7q:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/8468c931ddfc91a273bdd015e90826ba4f6a9e99/DscResource.DocumentationHelper/readme.md#L24)):*
<details><summary><i>Previously, KarolKaczmarek (Karol Kaczmarek) wrote…</i></summary>
> > p this specific bit and just let it ignore comment lines, and I a
> typo: resource
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/171)*

**Comment by KarolKaczmarek** [comment]
Thanks @BrianFarnhill for implementing feedback! Merging.

**Pull request merged**
