### PR TITLE
Initial Doc

### PR DESCRIPTION
**Pull request by athaynes**
This is a starting place for Issue #91 
I created a getting started guide for Pester, that is more focused on some test design decisions with Pester demos to highlight the concepts. There is room for more, but I wanted to get the initial doc up for review.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/189)

### CODE REVIEW

**Comment by dcrreynolds** [comment]
I would love to see an example added that covers testing exceptions and cases that should fail.

**Comment by athaynes** [comment]
I think I have an idea on where to put that. I'll try to get an update in this weekend. Thanks for the additional idea.

**Comment by kwirkykat** [comment]
:+1: This is great! @athaynes Do you mind if I go ahead and merge it now or are you still making changes?

**Comment by athaynes** [comment]
@kwirkykat Go ahead and merge it in and we can edit it from there.

**Pull request merged**
