### PR TITLE
Update StyleGuideline with quotes guideline

### LINKED ISSUE #335: There are no guideline for when to use single quotes and double quotes
When doing review I always enforced the use of single quotes instead of double quotes around strings when there is no variable to evaluate in the string. But I realized now that there are actually no specific guideline around that in either StyleGuidline.md or BestPractices.md. 
All other guidelines do use single quotes around strings, so probably from there I have picked it up and started to enforced it (and probably because that is the way I code by default).

I suggest we should add a guideline in BestPractices.md saying that using double quotes around strings should be avoided where possible.

**Bad:**
`"String that do not evaluate variable"`

**Good:**
`'String that do not evaluate variable'`

**Good:**
`"String that evaluate variable $($SomeObject.SomeProperty)"`

Anyone has thoughts on this?

### PR DESCRIPTION
**Pull request by johlju**
*This does not mean that all repos need to be updated to align with this.*

Fixes #335

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/389)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO or anyone else, please review this when you got a chance. Thanks! 🙂

**Comment by PlagueHO** [comment]
Of course. Will jump on this tomorrow night.

**Comment by johlju** [comment]
@PlagueHO Do you have a chance looking over this one? No hurry though. 🙂

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[StyleGuidelines.md, line 238 at r1](https://reviewable.io/reviews/powershell/dscresources/389#-LEagxN22JO_B_CbfkMn:-LEagxN49lesFxz4AsMQ:b8mnub6) ([raw file](https://github.com/powershell/dscresources/blob/e136601a10df60969f241e1bc9ba3181d507e449/StyleGuidelines.md#L238)):*
> ```Markdown
> ### Correct use of single- and double quotes
> 
> Single quotes should always be used where applicable.
> ```

Maybe we could clarify a bit?

Single quotes should always be used to delimit string literals wherever possible. Double quoted string literals may only be used when it contains (`$`) expressions that need to be evaluated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/389)*

**Comment by johlju** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

---

*[StyleGuidelines.md, line 238 at r1](https://reviewable.io/reviews/powershell/dscresources/389#-LEagxN22JO_B_CbfkMn:-LEj4vg94LYbgLM88PF9:blyq5fw) ([raw file](https://github.com/powershell/dscresources/blob/e136601a10df60969f241e1bc9ba3181d507e449/StyleGuidelines.md#L238)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Maybe we could clarify a bit?

Single quotes should always be used to delimit string literals wherever possible. Double quoted string literals may only be used when it contains (`$`) expressions that need to be evaluated.
</blockquote></details>

Done. Thanks for the very improved text! :slightly_smiling_face: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/389)*

**Comment by johlju** [comment]
@PlagueHO Do you have time to sign-off on this too? 🙂

**Pull request merged**
