### PR TITLE
Updated test template

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Updated example as per #143 - this updated test template reflects the discussion from that issue around the structuring of unit tests for DSC resources, focusing on making them more scenario/functionality based as opposed to being based on the structure of the code.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/144)

### CODE REVIEW

**Comment by KarolKaczmarek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests.Template/unit_template.ps1, line 75 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/144#-KKtIY5Sk7g96ZlOUBi0:-KKtIY5Sk7g96ZlOUBi1:834153723) ([raw file](https://github.com/powershell/dscresources/blob/fa97e5276d8e2d6898bd952014f014e9011e4d8b/Tests.Template/unit_template.ps1#L75)):*
> ```PowerShell
> 
>         #TODO: Update the assertions below to align with the expected results of this state
>         It "Should return a specific value in the get method" {
> ```

How about stating the name of the method first?
e.g. "Set method should return a specific value"

this way we don't need to read the whole "it" section to figure out what given test case is focusing on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/144)*

**Comment by BrianFarnhill** [comment]
@nzspambot What type of example have you got in mind for that one? I haven't gotten around to adding localization support to my SharePointDsc module yet so I haven't got as much context of what would be useful to test in that regard.

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests.Template/unit_template.ps1, line 75 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/144#-KKtIY5Sk7g96ZlOUBi0:-KKupDU28kS5bbytD1g5:-499146009) ([raw file](https://github.com/powershell/dscresources/blob/fa97e5276d8e2d6898bd952014f014e9011e4d8b/Tests.Template/unit_template.ps1#L75)):*
<details><summary><i>Previously, KarolKaczmarek wrote…</i></summary>
> How about stating the name of the method first?
> e.g. "Set method should return a specific value"
> 
> this way we don't need to read the whole "it" section to figure out what given test case is focusing on.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/144)*

**Comment by BrianFarnhill** [comment]
@nzspambot So you're essentially looking to test that the expected verbose messages came out as well as the result then, yea? @KarolKaczmarek your thoughts?

Personally I'm not convinced on that - if I'm getting the desired output from the input then I'm happy with the code path I'm testing there. What value does checking the verbose messages add? Happy to be convinced if there is something I'm missing here though - just wanted to have the discussion

**Comment by tysonjhayes** [comment]
There are a number of cases I've seen where the only way to see if you've hit the right block of if statements is to check the verbose message, as it just returns a value otherwise. [xWebApplication](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1#L320) has a number of examples of this.

**Comment by KarolKaczmarek** [comment]
Another area where you may want to check against localized message are negative test cases and verifying we got the expected error message (another approach is to check for FullyQualifiedErrorId).

That being said, I'm not sure we should cover all these cases in template. I'd keep them as lightweight and possible and place examples how to test localized data etc. here: https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md 

We could mention this link in the template though.

**Comment by PlagueHO** [comment]
I'd definitely like to see a section added to the [Test Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) that we can add common test patterns to and keep the template as slim as possible. The common test patterns should also link to the real examples in other DSC repos where possible. The templates are looking good @BrianFarnhill.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/144#-:-KL9p790tfljLl9DMlZy:-744968193)*

**Comment by KarolKaczmarek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/144#-:-KLIfYkfuc-eRyPphI8W:980077401)*

**Comment by KarolKaczmarek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/144)*

**Pull request merged**
