### PR TITLE
Update StyleGuidelines.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/135)

### CODE REVIEW

**Comment by alexandair** [comment]
@eslesar Could someone from the team check this PR?

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[StyleGuidelines.md, line 389 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/135#-KJHWmMvam6vSNo3jtHj:-KJHWmMwSiYZe4nj1NJk:1538976668) ([raw file](https://github.com/powershell/dscresources/blob/e43a29aecbc2efc2a7b842586878d1b2fb37642b/StyleGuidelines.md#L389)):*
> ```Markdown
> 
> The above array of hash table objects is not consistent.
> *Care must be taken that each hash table or object does not exceed the 100 character maximum line width rule.*
> ```

`​hashtable` is the name of the object not `Hash Table`.

Suggested rewording (removing passive voice.)

Take care that each `HashTable` or `object` definition​ line does not exceed the 100 character maximum line width rule.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/135)*

**Comment by alexandair** [comment]
According to about_Hash_Tables the name of the type is "Hashtable" (System.Collections.Hashtable). The name of the data structure is "hash table".

**Comment by KarolKaczmarek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/135)*

**Comment by KarolKaczmarek** [comment]
LGTM, @TravisEz13 ?

**Pull request merged**
