### PR TITLE
DscResources: Added submodule NetworkingDsc, and xDisk

### PR DESCRIPTION
**Pull request by johlju**
- Changes to DscResources
  - Added deprecated resource module xDisk for reference.
  - Added renamed resource module NetworkingDsc, and removing old xNetworking.
  - Renamed xNetworking to NetworkingDsc in all related documents.
  - Minor updates to integration tests template.
  - Switched examples in TestGuidelines because the previous resource
    tests had gotten too complex for an easy example.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/382)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Do you mind reviewing this one too when you have a chance? VS Code trimmed a lot of white spaces, so it's look bigger than it is.

**Comment by PlagueHO** [comment]
Sweet as @johlju . I'll get on to this and the other ones tomorrow!

**Comment by PlagueHO** [comment]
Everything looks good, but just a question about whether or not we should still include deprecated resources as submodules?

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.gitmodules, line 196 at r1](https://reviewable.io/reviews/powershell/dscresources/382#-LCpZNneD_INsw44FLpl:-LCpZNneD_INsw44FLpm:b-z3onm3) ([raw file](https://github.com/powershell/dscresources/blob/485bdb054b7e524711e6f456e9370e2574227573/.gitmodules#L196)):*
> ```
> 	path = DscResources/ActiveDirectoryCSDsc
> 	url = https://github.com/PowerShell/ActiveDirectoryCSDsc
> [submodule "xDscResources/xDisk"]
> ```

Should this resource still be linked as a submodule if it is deprecated? Same goes for xTimezone.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/382#-:-LCp_7wI24K69sOnUkpL:b-rb543e)*

**Comment by johlju** [comment]
@PlagueHO Do you have time to sign-off on this one unless you have another argument for us leaving out xDisk? 🙂

**Comment by PlagueHO** [comment]
Doh! Sorry I missed this @johlju - I'll sign it off first thing tomorrow (only on my phone atm)

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/382#-:-LDGBsik-FKAUeZAgeDL:bnfp4nl)*

**Pull request merged**
