### PR TITLE
Activate Stale GitHub App (bot)

### PR DESCRIPTION
**Pull request by johlju**
This will active the GitHub App Stale that was configured against this repo.

As per issue https://github.com/PowerShell/DscResources/issues/401.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/402)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Do you mind proof reading this before I merge? 🙂

**Comment by PlagueHO** [comment]
Good stuff - just some minor grammar tweaks.

I am wondering if 14 days before stale is quite short - I know I try to keep up but it is pretty difficult - so I'd worry that there would be a lot of abandoned labels showing up.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.github/stale.yml, line 38 at r2](https://reviewable.io/reviews/powershell/dscresources/402#-LEIr3oM1CmcflVxwYHq:-LEIr3oM1CmcflVxwYHr:bnwooe3) ([raw file](https://github.com/powershell/dscresources/blob/26eb59ef534262a9ccfd80152c7a11bb76e4b38e/.github/stale.yml#L38)):*
> ```
> If the issue is label
> ```
->
If the issue is labelled

---

*[.github/stale.yml, line 40 at r2](https://reviewable.io/reviews/powershell/dscresources/402#-LEIr9lH6vWRSS19v0H_:-LEIr9lH6vWRSS19v0Ha:bg8xju5) ([raw file](https://github.com/powershell/dscresources/blob/26eb59ef534262a9ccfd80152c7a11bb76e4b38e/.github/stale.yml#L40)):*
> ```
>     the issue will not auto-close.
> ```
->
then the issue will not auto-close.

---

*[.github/stale.yml, line 43 at r2](https://reviewable.io/reviews/powershell/dscresources/402#-LEIrFLF32oHURWu2n_3:-LEIrFLF32oHURWu2n_4:b-x5xeo5) ([raw file](https://github.com/powershell/dscresources/blob/26eb59ef534262a9ccfd80152c7a11bb76e4b38e/.github/stale.yml#L43)):*
> ```
> This issue has be automatically close because it is has not had activity from
> ```
->
This issue has been automatically closed because it is has not had activity from

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/402#-:-LEIrQWZEKCSk8BgOWqM:bvzwpso)*

**Comment by johlju** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[.github/stale.yml, line 38 at r2](https://reviewable.io/reviews/powershell/dscresources/402#-LEIr3oM1CmcflVxwYHq:-LEJA_53EG6ZCHD0FuX_:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/26eb59ef534262a9ccfd80152c7a11bb76e4b38e/.github/stale.yml#L38)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> If the issue is label
> ```
->
If the issue is labelled
</blockquote></details>

Done.

---

*[.github/stale.yml, line 40 at r2](https://reviewable.io/reviews/powershell/dscresources/402#-LEIr9lH6vWRSS19v0H_:-LEJAa-30xzI9290vbwS:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/26eb59ef534262a9ccfd80152c7a11bb76e4b38e/.github/stale.yml#L40)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
>     the issue will not auto-close.
> ```
->
then the issue will not auto-close.
</blockquote></details>

Done.

---

*[.github/stale.yml, line 43 at r2](https://reviewable.io/reviews/powershell/dscresources/402#-LEIrFLF32oHURWu2n_3:-LEJAv9g58UCtgimbC-M:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/26eb59ef534262a9ccfd80152c7a11bb76e4b38e/.github/stale.yml#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> This issue has be automatically close because it is has not had activity from
> ```
->
This issue has been automatically closed because it is has not had activity from
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/402)*

**Comment by johlju** [comment]
@PlagueHO Thanks for the review! Let's see how the `pulls:` keyword works in this repo. If it closes abandoned PRs here to.

**Pull request merged**
