### PR TITLE
Update text around new resource module submission

### LINKED ISSUE #356: How to do a new resource module submission
The text in [NewResourceModuleSubmissions.md](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) is not update to date on how a resource module should be submitted today. It should not be transferred as previously stated.

The below text is thoughts/suggestion on how the new text should read, and is up for discussion by the community. This is based on information found in the DscResources repository.

1. The new way to do a resource module submission is that the owner of the resource module repository is allowed to add the repository to the list of resource modules under [DscResources](https://github.com/PowerShell/DscResources/tree/master/DscResources) (by updating [.gitmodules](https://github.com/PowerShell/DscResources/blob/master/.gitmodules)).
1. The reason that the module no longer should be transferred is supportability. The maintainer (owner) and the community will contribute and give support to the resource module (in the owners repository) on a voluntary basis. But, if not otherwise mentioned in the resource module documentation [it should be considered unsupported](https://github.com/PowerShell/DscResources/blob/master/Supportability.md#who-provides-support-for-the-technologies-managed-by-dsc).
1. Prior to listing in DSC Resource repository under [DscResources](https://github.com/PowerShell/DscResources/tree/master/DscResources)
   - The repository must pass the [Quality Governance](https://github.com/PowerShell/DscResources/blob/master/Naming.md#quality-governance).
   - The community accepts, at a community call, that a resource module follows the guidelines set out for a [High Quality Resource Module](https://github.com/PowerShell/DscResources/blob/master/Naming.md#high-quality-resource-module).
1. No resource modules should be added to [xDscResources](https://github.com/PowerShell/DscResources/tree/master/xDscResources) since [experimental ('x') convention is deprecated](https://github.com/PowerShell/DscResources/blob/master/Naming.md#deprecated-experimental). *The resource modules listed today under [xDscResources](https://github.com/PowerShell/DscResources/tree/master/xDscResources) is meant to be converted to the new naming convention (the name suffixed with 'Dsc') and moved to [DscResources](https://github.com/PowerShell/DscResources/tree/master/DscResources) when they meet the criteria for a resource module submission.*

### PR DESCRIPTION
**Pull request by johlju**
- Update text around new resource module submission
- Adds new issue templates
  - Issue template for 'New resource module submission'
  - Issue template for 'General questions'
  - Issue tempate for 'Problem with resource module'

Fixes #356

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/398)

### CODE REVIEW

**Comment by johlju** [comment]
@mgreenegit could you please look at the text in these files for accuracy?

* NewResourceModuleSubmissions.md
* .github/ISSUE_TEMPLATE/New_resource_module_submission.md

@PlagueHO could you please proof read the text when you have a chance? 😃

**Comment by johlju** [comment]
@kwirkykat Maybe you would like to look over these as well?

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[NewResourceModuleSubmissions.md, line 1 at r1](https://reviewable.io/reviews/powershell/dscresources/398#-LDuFt-X2PUZUo6oHgzd:-LDuFt-X2PUZUo6oHgze:b-32vi5i) ([raw file](https://github.com/powershell/dscresources/blob/b899c99aa1cab6a481c060c26ab0db5e6e4d4d9c/NewResourceModuleSubmissions.md#L1)):*
> ```Markdown
> # How to do a resource module submission
> ```

BTW, might read better:
do -> perform

---

*[NewResourceModuleSubmissions.md, line 18 at r1](https://reviewable.io/reviews/powershell/dscresources/398#-LDuGNXh6DjXVYkTGsTx:-LDuGNXh6DjXVYkTGsTy:b64bxlg) ([raw file](https://github.com/powershell/dscresources/blob/b899c99aa1cab6a481c060c26ab0db5e6e4d4d9c/NewResourceModuleSubmissions.md#L18)):*
> ```Markdown
> 
> When you think your resource module is ready for listing in DSC Resource Kit,
> then the first step is to create a new issue with the *New resource module submission* issue
> ```

BTW: might read better:
with -> using

---

*[NewResourceModuleSubmissions.md, line 28 at r1](https://reviewable.io/reviews/powershell/dscresources/398#-LDuGYUK3HDDKvhr5v2w:-LDuGYUK3HDDKvhr5v2x:b-k2s4iz) ([raw file](https://github.com/powershell/dscresources/blob/b899c99aa1cab6a481c060c26ab0db5e6e4d4d9c/NewResourceModuleSubmissions.md#L28)):*
> ```Markdown
> 
> The maintainer (owner) of the resource module, and the community, will contribute
> and give support to the resource module (in the owners repository) on a voluntary
> ```

BTW:
give support to the resource module -> support the resource module

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/398)*

**Comment by johlju** [comment]
@plagueho  Thanks for the proof reading - I was expecting more review comments :smiley: 

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/398#-:-LDuxNB626AxTxQgWrCn:b-h67z71)*

**Comment by johlju** [comment]
I won't merge this until it's approved by either @kwirkykat or @mgreenegit

**Comment by johlju** [comment]
@kwirkykat @mgreenegit I will self-review this in a day or so, and then I will merge this. If you have any comment, please review until then. 🙂

**Pull request merged**
