### PR TITLE
Update style guideline how empty hashtable should be written

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Update style guideline how empty hashtable should be written to accommodate the custom rule.

#### This Pull Request (PR) fixes the following issues
None

#### Task list

- [x] This PR changes documentation

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/531)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO or @gaelcolas please review this when you have time. I will send in a PR to update DSC Community website as well.

**Comment by johlju** [comment]
Fixing that, give me a second :)

**Comment by johlju** [comment]
Updated adding that a space between braces are bad as well. 🙂

**Comment by gaelcolas** [comment]
sorry for the delay. merged now.

**Pull request merged**
