### PR TITLE
adding agenda for next community call

### PR DESCRIPTION
**Pull request by gaelcolas**
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/495)

### CODE REVIEW

**Comment by swngdnz** [comment]
Not found:

https://github.com/PowerShell/DscResources/CommunityCalls/DSC%20Resource%20Kit%20Community%20Call%20ICS.zip

As has been true for over a year now.

Thanks.

Regards,
Michael B.

**Comment by gaelcolas** [comment]
Thanks for the heads up @swngdnz will update the link. The ICS has been fixed though, just the link seems wrong.

**Comment by gaelcolas** [comment]
Here's [the correct link](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/DSC%20Resource%20Kit%20Community%20Call%20ICS.zip)

**Comment by swngdnz** [comment]
That seems to work. At least I have a meeting for 8-May at 15:00 eastern time.

Thanks.

Regards,
Michael B.

**Comment by gaelcolas** [comment]
Ah, you pointed me to a mistake! Thanks again! I put 9th of May, because of my timezone!

**Comment by swngdnz** [comment]
So what is the correct link?

Thanks.

Regards,
Michael B.

**Comment by gaelcolas** [comment]
The link was and is OK. Just the Agenda.md and its parent folder had an error. I'm pushing the correction and will merge it in.

**Comment by swngdnz** [comment]
Thank you!

Thanks.

Regards,
Michael B.

**Pull request merged**
