### PR TITLE
Best Practices: Update documentation around localization

### LINKED ISSUE #236: Discussion: How to translate logs when resources are localized
When a user recently submitted an issue over at xSQLServer, and added an output log mostly in Spanish I had an epiphany. The reason the log was still partly in English was because the resource are not yet localized in Spanish. So the verbose output in the logs contained the English localization strings.
When that resource is localized to Spanish and other languages I think we need some way to "translate" the logs (other than a online translate service). 

I'm glancing over at PSDSCResource now, because I'm about to change the localization over at xSQLServer. But looking at the code I see there are no unique way to distinguish a particular localized string (except the key). 

Example snippet from MSFT_WindowsOptionalFeature:
```
ConvertFrom-StringData @'
    GetTargetResourceStartMessage = Started Get-TargetResource on the {0} feature.
'@

Write-Verbose -Message ($LocalizedData.GetTargetResourceStartMessage -f $Name)
```

Should we have a "unique ID" in each localized string? Or should we output the key `GetTargetResourceStartMessage` as well? Or is there a more clever way of doing this?

### PR DESCRIPTION
**Pull request by johlju**
- Changes to Best Practices
  - Update documentation around localization.
  - Updated documentation with localization string ID suffix (issue #236).

Fixes #236 

*This partly documentation we had in the SqlServerDsc repository that can be moved here instead.*

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/403)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Would you mind review this? When you have time, no hurry! 🙂 Is it appropriate to have this information in this documentation?

**Comment by PlagueHO** [comment]
Just some minor bits! Looking great though @johlju!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[BestPractices.md, line 936 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWHTi8BqTNCQKZudRJ:-LEWHTi8BqTNCQKZudRK:b-sg78u7) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L936)):*
> ```Markdown
> In each resource folder there should be at least one localization folder for
> english language 'en-US'. Add other localization folders as appropriate, the
> correct folder name can be found when running `Get-UICulture` on the node that
> ```

found when -> found by

---

*[BestPractices.md, line 937 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWHZDOAtfGJxEvWmT5:-LEWHZDOAtfGJxEvWmT6:b-knx5kw) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L937)):*
> ```Markdown
> english language 'en-US'. Add other localization folders as appropriate, the
> correct folder name can be found when running `Get-UICulture` on the node that
> has a UI culture to build strings for. There is also the list of
> ```

has a UI culture installed that the strings are being built for.

---

*[BestPractices.md, line 943 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWHrIXB6pjlJzSh_1j:-LEWHrIXB6pjlJzSh_1k:b-6nfxf9) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L943)):*
> ```Markdown
> 'MSFT_\<ResourceName\>.strings.psd1' (e.g. 'MSFT_Folder.strings.psd1').
> Each localized string file should contain the following with the correct
> localization key and accompanying localization string value (example builds on
> ```

(the example uses the friendly resource name of 'Folder')

---

*[BestPractices.md, line 957 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWI2dDA-lVcERtk-ZG:-LEWI2dDA-lVcERtk-ZH:bciipgh) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L957)):*
> ```Markdown
> ```
> 
> The folder structure should look like the below when using the previous example.
> ```

Might read better as: When using the previous example, the folder structure would look like the following:

---

*[BestPractices.md, line 972 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWIqf7EKcJ1SGkKaCd:-LEWIqf7EKcJ1SGkKaCe:bgl51b4) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L972)):*
> ```Markdown
> To easier debug localized verbose logs, and to find the correct localized string
> key in the code, it is recommended to use a hard coded ID on each localized key's
> string value. That ID must be the same across the localized language folders,
> ```

BTW, Maybe: localized language folders -> localized language files?

---

*[BestPractices.md, line 979 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWIdUzBG6l2HbYPlpL:-LEWIdUzBG6l2HbYPlpM:bfjf1sv) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L979)):*
> ```Markdown
> > represented in each localization folder for that resource.
> 
> **Format:** `(ID:yyyyZZZZ)`
> ```

I totally forgot we were doing this! Awesome- it reminded me! :grin:

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/403#-:-LEWJgY-3LGFDZR5x0Pn:b-llpfm3)*

**Comment by johlju** [comment]
Thanks for the proof reading!  :smiley: 

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[BestPractices.md, line 936 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWHTi8BqTNCQKZudRJ:-LEZIJFh6tQvHc-qEXUD:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L936)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

found when -> found by
</blockquote></details>

Done.

---

*[BestPractices.md, line 937 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWHZDOAtfGJxEvWmT5:-LEZIP2DE-AOU-wfWw_R:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L937)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

has a UI culture installed that the strings are being built for.
</blockquote></details>

Done.

---

*[BestPractices.md, line 943 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWHrIXB6pjlJzSh_1j:-LEZIPig5VGtcdUUOBjF:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L943)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

(the example uses the friendly resource name of 'Folder')
</blockquote></details>

Done.

---

*[BestPractices.md, line 957 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWI2dDA-lVcERtk-ZG:-LEZIR9y6PWPVJgJsCDw:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L957)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Might read better as: When using the previous example, the folder structure would look like the following:
</blockquote></details>

Done.

---

*[BestPractices.md, line 979 at r1](https://reviewable.io/reviews/powershell/dscresources/403#-LEWIdUzBG6l2HbYPlpL:-LEZIUe02fPefXR7HSeR:b-z9ukxe) ([raw file](https://github.com/powershell/dscresources/blob/a6a8dd62919b7d5d93800f0c20ef18740719187b/BestPractices.md#L979)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I totally forgot we were doing this! Awesome- it reminded me! :grin:
</blockquote></details>

Yes the issue was about to close by Stale, so needed it to be documented somewhere ;)

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/403#-:-LEZIfI46C9PMw3gz3il:b-k5gsu0)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/403#-:-LEag1sP1FKOf2_IyEfK:bnfp4nl)*

**Pull request merged**
