### PR TITLE
Converted Invoke-Expression to & in Integration Test Template -Fixes #163

### LINKED ISSUE #163: Convert Invoke-Expression to & in Integration Test Template
In this line:
https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1#L51

Convert:
```powershell
Invoke-Expression -Command "$($script:DSCResourceName)_Config -OutputPath `$TestEnvironment.WorkingFolder"
```

To:
```powershell
& "$($script:DSCResourceName)_Config" -OutputPath $TestEnvironment.WorkingFolder
```

### PR DESCRIPTION
**Pull request by PlagueHO**
As per @kwirkykat comments in this PR comment:
https://reviewable.io/reviews/plagueho/systemlocaledsc/2#-KO7S2PMondhGNCQyH4I:-KO7S2PNfY1QHQpUYQep:-152257556

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/165)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 22 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/165#-KOBhw2-Cjsg3pIP1oYI:-KOBhw2-Cjsg3pIP1oYJ:1927103568) ([raw file](https://github.com/powershell/dscresources/blob/dcebbe1c426e84425677a77685d0779707468128/Tests.Template/integration_template.ps1#L22)):*
> ```PowerShell
> #region HEADER
> # Integration Test Template Version: 1.1.1
> [String] $moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Why did you change this?

---

*[Tests.Template/integration_template.ps1, line 32 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/165#-KOBi1ZLsiMMrv_NPr0_:-KOBi1ZLsiMMrv_NPr0a:-71127325) ([raw file](https://github.com/powershell/dscresources/blob/dcebbe1c426e84425677a77685d0779707468128/Tests.Template/integration_template.ps1#L32)):*
> ```PowerShell
> $TestEnvironment = Initialize-TestEnvironment `
>     -DSCModuleName $Global:DSCModuleName `
>     -DSCResourceName $Global:DSCResourceName `
> ```

Why is this changing back to the global scope?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/165)*

**Comment by PlagueHO** [comment]
Sorry @kwirkykat - it was a long day yesterday and I bungled this PR. I'll re-do it when I get to work in a little bit.

**Comment by kwirkykat** [comment]
@PlagueHO No worries. The scoping on the variables may actually have to be changed back to global since Pester doesn't seem to like script variables...

**Comment by PlagueHO** [comment]
@kwirkykat - Ok. All fixed now. Sorry about that again. Forgot to merge the latest changes to the upstream before I made my branch and submitted it.

**Comment by PlagueHO** [comment]
@kwirkykat - sorry about that. I've fixed it. Should be ok for merge now.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 22 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/165#-KOBhw2-Cjsg3pIP1oYI:-KP0aUToKkhKEFintQJJ:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/dcebbe1c426e84425677a77685d0779707468128/Tests.Template/integration_template.ps1#L22)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Why did you change this?
</details>
Done.

---

*[Tests.Template/integration_template.ps1, line 32 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/165#-KOBi1ZLsiMMrv_NPr0_:-KP0aV5SY39Pnt7wcAtc:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/dcebbe1c426e84425677a77685d0779707468128/Tests.Template/integration_template.ps1#L32)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Why is this changing back to the global scope?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/165#-:-KP0aWhvug23SekSWCJS:b-kz1ze7)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/165#-:-KPDyR8XHp2RNNFFs0x5:bnfp4nl)*

**Pull request merged**
