### PR TITLE
Update Styleguidelines and Testguidelines to meet Pester v4 - Fixes #330

### LINKED ISSUE #330: Update guidelines to the New Pester syntax
As of issue #327, the recently merged guideline should also change to reflect the new Pester syntax. 
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#capitalized-pester-assertions

Also the TestGuidelines.md should also be updated to be new Pester syntax. 

_Open this issue instead of adding on to issue #327 since that PR resolving has gone thru review and are about to be merged._

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR:
- Updates `StyleGuidelines.md`:
  - To meet Pester v4 guidelines 
- Updated `TestGuidelines.md`:
  - To meet Pester v4 guidelines
  - To remove Markdown rule violations

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/336)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[TestsGuidelines.md, line 90 at r1](https://reviewable.io:443/reviews/powershell/dscresources/336#-KzxqQPX1znzARHB8qjP:-KzxqQPX1znzARHB8qjQ:b-rx66e) ([raw file](https://github.com/powershell/dscresources/blob/81a114abc5dfdf6e7cb16069430256c9c94ff42d/TestsGuidelines.md#L90)):*
> ```Markdown
> ```
> 
> 1. Add any variables that are required to be accessed outside the module by unit tests to the ```Export-ModuleMember``` cmdlet in the DSC Resource:
> ```

This is seen as a new list, so this starts with 1. as well. Uncertain, but I think you must indent the code block and remove the spaces so it is rendered as a full list, or just change this to '2.'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/336)*

**Comment by PlagueHO** [comment]
Awesome! Thanks @johlju . I'll fix this PR up after Sunday as I'm taking a mini holiday. Cheers for reviewing.

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[TestsGuidelines.md, line 90 at r1](https://reviewable.io:443/reviews/powershell/dscresources/336#-KzxqQPX1znzARHB8qjP:-L-T4BJswaFYJ2TS4QXW:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/81a114abc5dfdf6e7cb16069430256c9c94ff42d/TestsGuidelines.md#L90)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This is seen as a new list, so this starts with 1. as well. Uncertain, but I think you must indent the code block and remove the spaces so it is rendered as a full list, or just change this to '2.'.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/336)*

**Comment by PlagueHO** [comment]
Thanks @Johlju - back from holiday now. I've made the changes.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/336#-:-L-T4D7Gjl9515FuzEb1:b-lmkr8c)*

**Comment by johlju** [comment]
:lgtm:

@kwirkykat Can you look at this and merge whenever you have a chance?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/336#-:-L-XXZduWCzPJcX5nTz8:bjhno8r)*

**Pull request merged**
