### PR TITLE
Adding Best Practice for NestedModules key

### LINKED ISSUE #274: Add Guideline for Exported Cmdlet Naming Conventions
To ensure that DSC Resource kit modules exported functions don't conflict with each other, we should add a naming policy around exported functions. See: https://github.com/PowerShell/DscResources/issues/273#issuecomment-305637218

### PR DESCRIPTION
**Pull request by johlju**
Fixes #274

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/393)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Can you review this when you have a chance? Sorry for throwing so many PR's at you, luckily they are small. 😃

**Comment by PlagueHO** [comment]
Just some very minor grammatical tweaks.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[BestPractices.md, line 912 at r1](https://reviewable.io/reviews/powershell/dscresources/393#-LDozltH4V80ynPZI5dW:-LDozltH4V80ynPZI5dX:byd6jxj) ([raw file](https://github.com/powershell/dscresources/blob/d36f188cf739e3655f52ef6a9d8a7c2c4cbb8839/BestPractices.md#L912)):*
> ```Markdown
> 
> Since we don't use the `RootModule` key in the module manifest, we should not
> use `NestedModules` key to add modules that export functions that are shared
> ```

use `NestedModules` -> use the `NestedModules`

---

*[BestPractices.md, line 915 at r1](https://reviewable.io/reviews/powershell/dscresources/393#-LDp-a9C3U-6HspxAyOZ:-LDp-a9D1qI7PRHYSAIU:br66l63) ([raw file](https://github.com/powershell/dscresources/blob/d36f188cf739e3655f52ef6a9d8a7c2c4cbb8839/BestPractices.md#L915)):*
> ```Markdown
> between resource modules.
> 
> Normally a single module listed in `RootModule` key can restrict what is
> ```

Normally, a single list in the `RootModule` key, can restrict what is

---

*[BestPractices.md, line 919 at r1](https://reviewable.io/reviews/powershell/dscresources/393#-LDp-sPsAw3eoe-nEJy0:-LDp-sPsAw3eoe-nEJy1:b8xsilc) ([raw file](https://github.com/powershell/dscresources/blob/d36f188cf739e3655f52ef6a9d8a7c2c4cbb8839/BestPractices.md#L919)):*
> ```Markdown
> we can't restrict what is exported, so every nested module will export all the
> commands (or all the commands restricted by `Export-ModuleMember` in that
> individual nested module). If two resource modules would use this method that
> ```

It two resource modules were to use the `NestedModules` method, it would result in one of them being unable to install since they have conflicting exported commands.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/393#-:-LDp0G36Bg5Yi31nmVun:b-izo0df)*

**Comment by johlju** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[BestPractices.md, line 912 at r1](https://reviewable.io/reviews/powershell/dscresources/393#-LDozltH4V80ynPZI5dW:-LDpKsue83VracMWP3WU:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/d36f188cf739e3655f52ef6a9d8a7c2c4cbb8839/BestPractices.md#L912)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

use `NestedModules` -> use the `NestedModules`
</blockquote></details>

Done.

---

*[BestPractices.md, line 915 at r1](https://reviewable.io/reviews/powershell/dscresources/393#-LDp-a9C3U-6HspxAyOZ:-LDpKtjTD0LX8HS7vmBf:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/d36f188cf739e3655f52ef6a9d8a7c2c4cbb8839/BestPractices.md#L915)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Normally, a single list in the `RootModule` key, can restrict what is
</blockquote></details>

Done.

---

*[BestPractices.md, line 919 at r1](https://reviewable.io/reviews/powershell/dscresources/393#-LDp-sPsAw3eoe-nEJy0:-LDpKysCBoADPhYgHufx:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/d36f188cf739e3655f52ef6a9d8a7c2c4cbb8839/BestPractices.md#L919)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

It two resource modules were to use the `NestedModules` method, it would result in one of them being unable to install since they have conflicting exported commands.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/393)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/393#-:-LDuEYYo5pzOBUCk4_Qz:bnfp4nl)*

**Pull request merged**
