### PR TITLE
Added Community Maintained Sub-modules - Fixes #361

### LINKED ISSUE #361: Include Community Maintained Resources
I will submit the following of my modules:

- [WSManDsc](https://github.com/PlagueHO/WSManDsc)
- [FSRMDsc](https://github.com/PlagueHO/FSRMDsc)
- [FileContentDsc](https://github.com/PlagueHO/FileContentDsc)
- [iSCSIDsc](https://github.com/PlagueHO/iSCSIDsc)

I'll submit these in the same PR to save work :grin:

### PR DESCRIPTION
**Pull request by PlagueHO**
I added my 4 HQRM resource modules as community maintained submodules.

I also corrected the names of a couple of the DSC Resource kit modules I maintain.

I also corrected a markdown error in Maintainers.MD.

Question: Should we also add a new section to the maintainers to list the fully community maintained modules? All good either way.

@johlju - would you mind reviewing for me when you get a moment?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/powershell/dscresources/362#-LAw7RjR3QI7Ijo-ShO1:-LAw7RjR3QI7Ijo-ShO2:b-u2ctbp) (no related file):*
We should add the maintainer(s) for the linked resources modules as well. Should we add them to the same maintainers list or should we add a section 'Maintainers of linked community resource modules'?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362)*

**Comment by johlju** [comment]
Some thoughts (went thought this list https://github.com/PowerShell/DscResources/pull/346#issuecomment-371041953)

- @PlagueHO The code of conduct in your repos might need to be modified slightly. Microsoft's one reference to e-mail Microsoft. I think they should e-mail to an address that your read. 🤔 
Read the section [Can I use this Code of Conduct in my projects?](https://opensource.microsoft.com/codeofconduct/faq/#caniuse)
- Should include the metadata tag 'DSCResourceKit' in the module manifest (when approved). Seems reasonably if approved to be linked here.

**Comment by PlagueHO** [comment]
Good catch @johlju

What I decided to do after working through the FAQ and trying to adapt the Microsoft one is to create my own version using the Open Code of Conduct Template (referenced at the bottom of the Microsoft one). I've included this in a separate MD file in each of my repos and now refer to that.

I'll add the meta data tag once this PR goes through.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io/reviews/powershell/dscresources/362#-LAw7RjR3QI7Ijo-ShO1:-LB0CrV53K4M4p69nRlt:brbeku0) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

@plagueho I saw that you asked the same question. I suggest we create a new section under the Maintainers section 8as per above), and list all linked repos there. Would that work?
</blockquote></details>

I'll add a new section to the maintainers. Let me know what you think.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362#-:-LB0CRKX5-OaRTNREsqt:b-t07xzr)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Maintainers.md, line 95 at r2](https://reviewable.io/reviews/powershell/dscresources/362#-LB1fhNnDrkvixEpp-61:-LB1fhNnDrkvixEpp-62:btmynnt) ([raw file](https://github.com/powershell/dscresources/blob/9fbecde7651646f701fb95d10267440ca6ea7c36/Maintainers.md#L95)):*
> ```
> kit
> ```

Upper 'K' on 'Kit'

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362)*

**Comment by PlagueHO** [comment]
@johlju - all done!

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Maintainers.md, line 95 at r2](https://reviewable.io/reviews/powershell/dscresources/362#-LB1fhNnDrkvixEpp-61:-LB2LRit2z7Oum3qzc_Q:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/9fbecde7651646f701fb95d10267440ca6ea7c36/Maintainers.md#L95)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> kit
> ```

Upper 'K' on 'Kit'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362#-:-LB2LSfW3OgSJFh0gXNh:b-82pp50)*

**Comment by PlagueHO** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/dscresources/362#-LAw7RjR3QI7Ijo-ShO1:-LB82CBAAYU17f6y381H:beyh20i) (no related file):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Sweet - I'll get onto this first thing tomorrow!
</blockquote></details>

@Johlju - all done. Let me know what you think as I wasn't 100% sure on the new sentence structure.

---

*[.gitmodules, line 4 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5L55m92TJWCYHc-4F:-LB7yXBCDpsQ8eGnbq7r:bs8i65t) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/.gitmodules#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> xDscResources
> ```

Should be moved to 'DscResources'. Same for the rest of the renamed resource modules.
</blockquote></details>

Done. Good catch.

I also noticed that there was still xSharePoint in there so I remove it (it redirects to SharePointDsc anyway - so we'd end up with this twice).

---

*[Maintainers.md, line 93 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5MsS90RYbh6zyMDoY:-LB8-iRd312HzCAfyyao:b-6ysbgz) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/Maintainers.md#L93)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I asked @mgreenegit to look at this offline. He suggest that we merge these two tables, he thought your text should say that for all resources, except xPSDesiredStateConfiguration. So, could you please do this

1. Merge this table with the one above.
2. Move the text that are currently under 'Non-Microsoft DSC Resource Module Maintainers' to the section 'Current Maintainers'.
3. Update the text with my review comments (proof read my text ;).
</blockquote></details>

Done - I think - there was a few sentences under this section, so I wasn't sure about replacing them all with the text. Let me know what you think.

One thing I was thinking about in the table:

For my resources I've linked to my repo in GitHub - but should we do this for all repos as a handy link? I can do this pretty easily but didn't want to do it if it was just "something else for us to maintain". What do you think?

---

*[Maintainers.md, line 95 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5NIQq-VtTIX__zuYz:-LB807AQ14Fvu0Tds-80:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/Maintainers.md#L95)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Some modules listed in the DSC Resource Kit are
> ```

"Resource modules listed in the DSC Resource Kit, except xPSDesiredStateConfiguration, are ..."
</blockquote></details>

Done.

---

*[Maintainers.md, line 96 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5NdD61A5k3677P790:-LB807YS-dsSzRhBMeZ_:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/Maintainers.md#L96)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> by non-Microsoft community members
> ```

"by community members" 
</blockquote></details>

Done.

---

*[Maintainers.md, line 96 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5NidX9LxDATLNA6Wm:-LB808305je-p--qGGH8:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/Maintainers.md#L96)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> modules
> ```

"resource modules"
</blockquote></details>

Done.

---

*[Maintainers.md, line 98 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5O1Qe-lPrRW4IHeJG:-LB81gc6Dw3OEHgXgPoM:bs7wumx) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/Maintainers.md#L98)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Issues or questions relating to these modules should be raised within the
> community member's repository.
> ```

"Issues or questions relating to these resource modules should be raised within the resource modules repository."
</blockquote></details>

Done. 

---

*[Maintainers.md, line 100 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5OONT-506kmbmWoYm:-LB82AJS-3wQyB3hGFOZ:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/Maintainers.md#L100)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This sentence become obsolete
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Maintainers.md, line 93 at r3](https://reviewable.io/reviews/powershell/dscresources/362#-LB5MsS90RYbh6zyMDoY:-LBKwIl_4JGWvIoMZoXm:b-7mjcqe) ([raw file](https://github.com/powershell/dscresources/blob/6966ca65e37365f0aa756ab4d3fe0893ee755da5/Maintainers.md#L93)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Done - I think - there was a few sentences under this section, so I wasn't sure about replacing them all with the text. Let me know what you think.

One thing I was thinking about in the table:

For my resources I've linked to my repo in GitHub - but should we do this for all repos as a handy link? I can do this pretty easily but didn't want to do it if it was just "something else for us to maintain". What do you think?
</blockquote></details>

LGTM. The text looks good to me. I just need to get this signed off before merging. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362)*

**Comment by PlagueHO** [comment]
Thanks @Johlju - I fixed the merge conflicts now.

**Comment by johlju** [comment]
:lgtm:

@kwirkykat @mgreenegit I merging this now. 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/362#-:-LBe42_V70QLMZjJkARz:bqda1w9)*

**Comment by johlju** [comment]
@PlagueHO Hmm.. there are still merge conflicts? 🤔

**Comment by johlju** [comment]
@PlagueHO Never mind, it was me having the wrong type of merge (merge and squash worked, but not reabse and merge). Merged,

**Pull request merged**
