### PR TITLE
Update appveyor.yml template - Fixes #347

### LINKED ISSUE #347: Update AppVeyor YAML template for resource modules
I suggest we update the template for appveyor.yml at this location https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/appveyor.yml with a more current one. 

I propose the below which uses the "default model"  and will run all the default common tests, with the option for the maintainer to opt-in for the rest of the test when so is possible.

```
#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.{build}.0
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @()
#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask
```

### PR DESCRIPTION
**Pull request by johlju**
I propose this as the default template for (new) resource modules. The template uses the "default model" and will run all the default common tests, with the option for the maintainer to opt-in for the rest of the test when so is possible.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/348)

### CODE REVIEW

**Comment by bitbon57** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/348#-:-L7noZOgGLVYtOvbdXs9:bnfp4nl)*

**Comment by bitbon57** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/348)*

**Comment by johlju** [comment]
@bitbon57 thanks for the review! 

@kwirkykat when you have time, can you look over this and merge? Thanks

**Comment by bitbon57** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://beta.reviewable.io/reviews/powershell/dscresources/348#-L7q-ubb9jOb4L-v4ue3:-L7q-ubb9jOb4L-v4ue4:b3nio) (no related file):*
ี

---

*[DscResource.Template/appveyor.yml, line 45 at r1](https://beta.reviewable.io/reviews/powershell/dscresources/348#-L7npHDMxRuMCFjomj_L:-L7npHDMxRuMCFjomj_M:bn6rymq) ([raw file](https://github.com/powershell/dscresources/blob/1a89f3337fee8fb89315a6cf4c101c174fee52b1/DscResource.Template/appveyor.yml#L45)):*
> ```YAML
> # scripts to run before deployment
> deploy_script:
>     - ps: |
> ```



---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/dscresources/348)*

**Pull request merged**
