### PR TITLE
Updated GettingStartedWithPester

### LINKED ISSUE #91: Include some pointers on learning pester
Perhaps just this link:
https://github.com/pester/Pester#for-further-learning

### PR DESCRIPTION
**Pull request by johlju**
- Fixed lint errors.
- Added note linking to up-to-date instructions on how to
  install Pester.
- Added a note linking to further reading about Pester (issue #91).

Fixes #91

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/400)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO could you review this one when you got a chance?

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[GettingStartedWithPester.md, line 606 at r1](https://reviewable.io/reviews/powershell/dscresources/400#-LDzmQu47dXRfxRnwure:-LDzmQu47dXRfxRnwurf:b-tquv0b) ([raw file](https://github.com/powershell/dscresources/blob/3ccaed9edab18c0e4930c0d8c7adcdd90181743e/GettingStartedWithPester.md#L606)):*
> ```Markdown
> 1. It verifies that you have added the new functionality without breaking any
>    existing functionality in the process.
> 2. All of the mocks were written first, so theoretically, no changes should occur in unit testing
> ```

Shouldn't this be a 1?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/400)*

**Comment by johlju** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[GettingStartedWithPester.md, line 606 at r1](https://reviewable.io/reviews/powershell/dscresources/400#-LDzmQu47dXRfxRnwure:-LE95im44jGkXALauGwT:b-896fix) ([raw file](https://github.com/powershell/dscresources/blob/3ccaed9edab18c0e4930c0d8c7adcdd90181743e/GettingStartedWithPester.md#L606)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Shouldn't this be a 1?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/400)*

**Comment by johlju** [comment]
@PlagueHO when you have time, could you sign off on this?

**Comment by PlagueHO** [comment]
Absolutely @johlju - I'll get this done this weekend. Unfortunately it's end of financial year so my all my time is tied up doing performance reviews for my team :cry: but I'll be done by the weekend.

**Comment by johlju** [comment]
@PlagueHO No worries, no hurry. Your team is more important! This can wait 😃

**Comment by PlagueHO** [comment]
Just have a few minutes tonight. Will definitely have some spare time this weekend to get the others done.

:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/400#-:-LG-0NhU5EUZu_3ZdEGi:b-h7cssf)*

**Comment by johlju** [comment]
@PlagueHO Thank you! No worries, do them when you feel you have time. 🙂

**Pull request merged**
