### PR TITLE
other small style fixes in templates

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/150)

### CODE REVIEW

**Comment by mbreakey3** [comment]
@TravisEz13 Do these changes look good?

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 22 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/150#-KNZKK9zlnWv8modRFbb:-KNZKK9zlnWv8modRFbc:-541294360) ([raw file](https://github.com/powershell/dscresources/blob/257615903997c221933cc07fd85b0e982a5f03c1/Tests.Template/integration_template.ps1#L22)):*
> ```PowerShell
> #region HEADER
> # Integration Test Template Version: 1.1.0
> [String] $moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

why was the type removed?

---

*[Tests.Template/unit_template.ps1, line 22 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/150#-KNZKQFAYqdbDW3bULx9:-KNZKQFAYqdbDW3bULxA:711325672) ([raw file](https://github.com/powershell/dscresources/blob/257615903997c221933cc07fd85b0e982a5f03c1/Tests.Template/unit_template.ps1#L22)):*
> ```PowerShell
> #region HEADER
> # Unit Test Template Version: 1.1.0
> [String] $moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

same - type removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/150)*

**Comment by mbreakey3** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests.Template/integration_template.ps1, line 22 \[r1\]](https://reviewable.io:443/reviews/powershell/dscresources/150#-KNZKK9zlnWv8modRFbb:-KNZMr9n8RSNb8fR0Q0d:1645029892) ([raw file](https://github.com/powershell/dscresources/blob/257615903997c221933cc07fd85b0e982a5f03c1/Tests.Template/integration_template.ps1#L22)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> why was the type removed?
</details>
I can put it back in

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/150)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/dscresources/150)*

**Pull request merged**
