### PR TITLE
Adds Office365DSC References into the DSCResources Kit

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Adds Office365DSC References into the DSCResources Kit

#### This Pull Request (PR) fixes the following issues
N/A

#### Task list
- [ ] This PR changes documentation

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/500)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dscresources/500)* status: all files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[.gitmodules, line 196 at r1](https://reviewable.io/reviews/powershell/dscresources/500#-LcpIes04oqhyzJptB2j:-LcpIes10JTVAbG7lKMU:b-xnb78k) ([raw file](https://github.com/powershell/dscresources/blob/031610f909217b091153a1193445cf88dd2543b0/.gitmodules#L196)):*
> ```
> [submodule "DscResources/Office365Dsc"]
> ```

I think this would have been added, and the correct reference in the DscResource folder if the submodule was added using `git submodule add https://github.com/<accountname>/<reponame> DscResources/<reponame>` (see issue template).
DId you run the `git submodule` command?

**Comment by gaelcolas** [comment]
I think change is in motion and next community call will be the time to reconsider this.

**Comment by gaelcolas** [comment]
As announced during the last community call, we'd love to have this as part of [dsccommunity](https://github.com/dsccommunity) when we start the transfer.
I'll get in touch with you @NikCharlebois in the next few weeks to discuss this.

**Comment by gaelcolas** [comment]
I'm closing this one as we'll probably transfer and archive this repository.
@NikCharlebois let me know if you want a particular listing in DSC Community.

**Pull request closed without merging**
