### PR TITLE
Deprecate xSmbShare

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
Deprecating this resource module xSmbShare.

*This PR should only be merged once the PR PowerShell/ComputerManagementDsc#211, and the PR https://github.com/PowerShell/xSmbShare/pull/31 is merged.*

#### This Pull Request (PR) fixes the following issues
As discussed in issue PowerShell/DscResources#374.

#### Task list

- [x] This PR changes documentation

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/499)

### CODE REVIEW

**Comment by gaelcolas** [comment]
Can you also make sure there's a PR on xSmbShare that updates the changelog and probably write a Warning message when imported.
Please reference it here so it's easier to track.

**Comment by johlju** [comment]
There are already a pending PR https://github.com/PowerShell/xSmbShare/pull/31 taking care of that. Although should we write a warning message in xSmbShare? We haven’t done that for any other deprecated module, and the resource do work for those that are using it. Do we want them to get a warning message each time the module is imported? But if we want that, how do I output a warning message the best way when a module is imported? :smile:

**Comment by gaelcolas** [comment]
Nah, no need. I thought I saw that done before :/ nvm!

Will merge after next Resource Kit release.

**Comment by johlju** [comment]
Waiting for the PR to be reviewed in ComputerManagementDsc. Hen that is merged I will take this one out of draft.

**Comment by PlagueHO** [comment]
@johlju - should be good to go with this one! :grin:

**Comment by johlju** [comment]
@gaelcolas ready for review.

**Pull request merged**
