### PR TITLE
Add files to DscResource.Template

### LINKED ISSUE #67: Differing Authors for Resources - No Enforced Standard
Although I see the benefit for accrediting the original Author of DSC resources, if these are maintained by Microsoft then shouldn't Microsoft be the Author of the modules?

When you run the below you can see that there are resources that are Authored differently to 'Microsoft Corporation'

```powershell
find-module x* -Tag DSC | Select-object Name,Author | Group-Object -Property Author 
````
This makes Discoverability for all these resources more difficult than it should be especially when you only want to download the x modules that are endorsed and developed by Microsoft

### LINKED ISSUE #284: Add Visual Studio Code PowerShell extension formatting settings to DSC Resource template
The Visual Studio Code PowerShell Extension contains many automatic formatting settings.

The default settings for these however will format PowerShell code in a way that conflicts with the StyleGuidelines. There may also be other settings in VS Code that can cause style violations and if anyone knows of them please feel free to make suggestions.

Therefore I propose:
1. Include a `.vscode\settings.json` file in the DSCResource Template containing the settings that are correct for DSC Resource Kit resources.
2. Start adding a `.vscode\settings.json` file to each of the DSC Resource kit resources.
3. Update `GettingStartedWithGitHub.md` to change the .gitignore recommendation to allow adding of .vscode\settings.json to tracked.

What I'd like to know is:
1. Are other repos already doing this and I'm just late to the party?
2. Is worth doing? My 2c is that it is.
3. If so, what are the settings that should be defined? Only settings that we actually have style guidelines should be defined IMHO.

I think these are the settings that should be used:
```
    "powershell.codeFormatting.openBraceOnSameLine": false,
    "powershell.codeFormatting.newLineAfterOpenBrace": false,
    "powershell.codeFormatting.newLineAfterCloseBrace": true,
    "powershell.codeFormatting.whitespaceBeforeOpenBrace": true,
    "powershell.codeFormatting.whitespaceBeforeOpenParen": true,
    "powershell.codeFormatting.whitespaceAroundOperator": true,
    "powershell.codeFormatting.whitespaceAfterSeparator": true,
    "powershell.codeFormatting.ignoreOneLineBlock": false,
    "powershell.codeFormatting.alignPropertyValuePairs": true
```

And for reference, here are all the settings defined by default:
```
  // Places open brace on the same line as its associated statement.
  "powershell.codeFormatting.openBraceOnSameLine": true,

  // Adds a newline (line break) after an open brace.
  "powershell.codeFormatting.newLineAfterOpenBrace": true,

  // Adds a newline (line break) after a closing brace.
  "powershell.codeFormatting.newLineAfterCloseBrace": true,

  // Adds a space between a keyword and its associated scriptblock expression.
  "powershell.codeFormatting.whitespaceBeforeOpenBrace": true,

  // Adds a space between a keyword (if, elseif, while, switch, etc) and its associated conditional expression.
  "powershell.codeFormatting.whitespaceBeforeOpenParen": true,

  // Adds spaces before and after an operator ('=', '+', '-', etc.).
  "powershell.codeFormatting.whitespaceAroundOperator": true,

  // Adds a space after a separator (',' and ';').
  "powershell.codeFormatting.whitespaceAfterSeparator": true,

  // Does not reformat one-line code blocks, such as "if (...) {...} else {...}".
  "powershell.codeFormatting.ignoreOneLineBlock": true,

  // Align assignment statements in a hashtable or a DSC Configuration.
  "powershell.codeFormatting.alignPropertyValuePairs": true,

  // Shows the integrated console when the PowerShell extension is initialized.
  "powershell.integratedConsole.showOnStartup": true,

  // Switches focus to the console when a script selection is run or a script file is debugged. This is an accessibility feature. To disable it, set to false.
  "powershell.integratedConsole.focusConsoleOnExecute": true,
```

Tagging maintainers:
@johlju, @bgelens, @BrianFarnhill, @RichardSiddaway, @raandree, @mbreakey3, @jcwalker, @tysonjhayes, @athaynes, @mhendric

### LINKED ISSUE #358: Add .codecov.yml to the DscResource template
We should add the [.codecov.yml](https://github.com/PowerShell/SqlServerDsc/blob/dev/.codecov.yml) file to the [DscResource template folder](https://github.com/PowerShell/DscResources/tree/master/DscResource.Template).

### PR DESCRIPTION
**Pull request by johlju**
Adding new files to the DscResource.Template - this is so that it is easier to reference these files from other repos.

*This is temporary until we get the new repo DscResource.Template as metioned in https://github.com/PowerShell/DscResources/issues/334.*

Fixes #67
Fixes #358
Fixes #284 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/388)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Could you review this too when you have a chance?

**Comment by johlju** [comment]
@PlagueHO This is the template for the default shared model - we should align this to the "joint model later" when issue https://github.com/PowerShell/DscResource.Tests/issues/225 is resolved. Or is updating with this unnecessary until we got the "new model" in place?

**Comment by PlagueHO** [comment]
I'll get onto all these reviews tonight - I'll finally have some spare time! :)

**Comment by johlju** [comment]
Yay! Thank you! :smile:

**Comment by PlagueHO** [comment]
Great job @johlju - will be +++ helpful! Just some minor bits.

---

Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @johlju)

---

*[DscResource.Template/CHANGELOG.md, line 6 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUCWkn05vwNxFI9Ofg:-LGUCWkoBgjfq7y8qogS:bt1nljs) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - Changes to ResourceName
>   - Descriptive text of the what was changed and why, and reference any issue it
> ```

Maybe:
```
- Text describing what was changed and why and a reference to any issues it closes
([issue #11111](https://github.com/PowerShell/SqlServerDsc/issues/11111)).
```

---

*[DscResource.Template/ResourceModule.psd1, line 38 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUElYT8X5-YgcHJ8XP:-LGUElYT8X5-YgcHJ8XQ:bq5vlpb) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/ResourceModule.psd1#L38)):*
> ```PowerShell
> 
>             # Tags applied to this module. These help with module discovery in online galleries.
>             Tags         = @('DesiredStateConfiguration', 'DSC', 'DSCResourceKit', 'DSCResource')
> ```

I wonder if the DSCResourceKit tag should probably only be added for resource in the Kit or linked to?

---

*[DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.psm1, line 22 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUGrbP6rjH51iGCbS4:-LGUGrbP6rjH51iGCbS5:b-pl25ao) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.psm1#L22)):*
> ```PowerShell
> 
>     return @{
>         Ensure = $ensure
> ```

Nitpick, non-blocking- align = ?

---

*[DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.schema.mof, line 5 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUGEMZCnRZyxuCWoNH:-LGUGEMZCnRZyxuCWoNI:b-sq01z0) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.schema.mof#L5)):*
> ```
> {
>     [Key, Description("Descriptive text for this property")] String MandatoryParameter;
>     [Key, Description("Descriptive text for this property")] String NonMandatoryParameter;
> ```

Shouldn't this be a `Write` rather than key if it is non-mandatory?

---

*[DscResource.Template/Examples/Resources/ResourceName/1-VeryShortDescription.ps1, line 14 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUG0olB3NGwZdcPjEI:-LGUG0olB3NGwZdcPjEJ:bamor25) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/Examples/Resources/ResourceName/1-VeryShortDescription.ps1#L14)):*
> ```PowerShell
>         ResourceName ShortNameForResource
>         {
>             Ensure               = 'Present'
> ```

Nitpick non-blocking, could the = be aligned? :grin:

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/388#-:-LGUH0tS2_kUDDog7ynR:b-c1zck8)*

**Comment by johlju** [comment]
Review status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @PlagueHO)

---

*[DscResource.Template/CHANGELOG.md, line 6 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUCWkn05vwNxFI9Ofg:-LGUZXhi6n_VSoOWyWNt:b-mvwmf) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/CHANGELOG.md#L6)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Maybe:
```
- Text describing what was changed and why and a reference to any issues it closes
([issue #11111](https://github.com/PowerShell/SqlServerDsc/issues/11111)).
```
</blockquote></details>

Done. Added a comma in there as well as I thought there was many 'and' after each other. Not sure if it reads better :slightly_smiling_face: 

---

*[DscResource.Template/ResourceModule.psd1, line 38 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUElYT8X5-YgcHJ8XP:-LGUZjc7CBSvNN_nypTo:bwz7jl7) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/ResourceModule.psd1#L38)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I wonder if the DSCResourceKit tag should probably only be added for resource in the Kit or linked to?
</blockquote></details>

Done. Agree, any resource modules linked to DSC Resource Kit should add that back at that time.

---

*[DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.psm1, line 22 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUGrbP6rjH51iGCbS4:-LGUZzQkEL0hRgNDILWn:bnn5cp8) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.psm1#L22)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick, non-blocking- align = ?
</blockquote></details>

Done. Added code to Test-function as well. Without your nit-pick I would have missed it! :smiley: 

---

*[DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.schema.mof, line 5 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUGEMZCnRZyxuCWoNH:-LGU_MwT7nvASg_kK575:b-eml6sm) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/DSCResources/MSFT_ResourceName/MSFT_ResourceName.schema.mof#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Shouldn't this be a `Write` rather than key if it is non-mandatory?
</blockquote></details>

Done. Doh, yes - copy paste error.

---

*[DscResource.Template/Examples/Resources/ResourceName/1-VeryShortDescription.ps1, line 14 at r2](https://reviewable.io/reviews/powershell/dscresources/388#-LGUG0olB3NGwZdcPjEI:-LGU_Rp-0GpOCLRr2pRo:bb6un1j) ([raw file](https://github.com/powershell/dscresources/blob/7ffad130deb52a0d589756534b7d338636b66a59/DscResource.Template/Examples/Resources/ResourceName/1-VeryShortDescription.ps1#L14)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick non-blocking, could the = be aligned? :grin:
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dscresources/388)*

**Pull request merged**
