### PR TITLE
Submit UpdateServicesDsc for DscResources repo listing

### LINKED ISSUE #187: xWSUS resource
There is a new resource available for review.  Thank you.
https://github.com/robwi/xWSUS

### PR DESCRIPTION
**Pull request by mgreenegit**
DSC Community - 

I would like to request for this DSC module, UpdateServicesDsc, to be considered for listing as a submodule in the DSCResources repo.

Closes #187 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dscresources/346)

### CODE REVIEW

**Comment by PlagueHO** [comment]
:lgtm:

Is this going to be the method going forward we should use for other community maintained DSC Resource modules? I have some modules I wanted to get linked to as well.

**Comment by johlju** [comment]
@mgreenegit A few comments about the UpdateServicesDsc. These are pointed out as of the https://github.com/PowerShell/DscResources/blob/master/Naming.md#quality-governance. Maybe some of these are up to the maintainer. Maybe some of these can be resolved once the repository is added to the DSC Resource Kit. 
This is a the first one, so this set precedence. 😄 

I did a really quick review of the UpdateServicesDsc repo. This is my thoughts, up for discussion.

* It should have a dev branch, and dev branch should be the default branch for new PR's.
* It has two branches that might be unnecessary. *This is probably up to the maintainer.*
* It doesn't seem connected to AppVeyor so new merges (and PR's) does not get tested (see commits https://github.com/mgreenegit/UpdateServicesDsc/commits/master)
* README.md referencing naming conventions including the use of 'c' suffix. This should be updated/removed.
* Doesn't use the normal template in the appveyor.yml - not sure if we have an official, but we should. Created a gist containing a template that could be merged as a template to DscResources; [Template appveyor.yml for default testing model for the DscResource.Tests framework](https://gist.github.com/johlju/465d67c9f7c32cd667c141979a08fb80)
* It should have Codecov added, and preferably README.md updated with badges (see example in [README.md](https://github.com/PowerShell/SqlServerDsc/blob/dev/README.md#branches)).
* It should have either a CONTRIBUTING.md file or a 'Contributing' section in the README.md file.
* Unit folder under Tests has a typo '.Unit' (starting with a '.'). *Might be a problem when tests are run in AppVeyor using test framework.*
* Unit tests should updated to using the latest unit test template from DscResources repository.
* Integration test does not actually test if the values were set.

**Comment by PlagueHO** [comment]
Great list @johlju - @mgreenegit - would you be up for accepting PRs to your repo so we can tweak these things?

**Comment by johlju** [comment]
Should we update the repo list in the Maintainers.md file as well for these new modules that get added?

**Comment by mgreenegit** [comment]
Good point.  I hope to get back to this today.

**Comment by johlju** [comment]
This was wrongly closed by Stale bot

**Comment by mgreenegit** [comment]
@PlagueHO @johlju @gaelcolas
Just FYI, I made a new round of updates this morning to try and bring this back for consideration in the  resource kit.

**Comment by mgreenegit** [comment]
since the original repo I submitted this from is long gone, I might have to restart the PR to resolve conflicts?  I just wanted to get feedback first.

**Comment by gaelcolas** [comment]
Having a look.
There's a few things I can see, will update with details shortly.

**Comment by gaelcolas** [comment]
Here's what I found so far.

1. New PR would be nice
2. README reference `SqlServerDsc` instead of `UpdateServiceDsc`
3. Your default branch (configured in GH) is master, please change to Dev
5.  You seem to have CodeCov only configured for the [master](https://codecov.io/gh/mgreenegit/UpdateServicesDsc/branch/master) branch (not [Dev](https://codecov.io/gh/mgreenegit/UpdateServicesDsc/branch/dev))
6. Unit folder under Tests has a typo '.Unit' (starting with a '.')
7.  Integration test does not actually test if the values were set.
8. CODE_OF_CONDUCT.md is missing but referenced in ReadMe.md
9. Add the repository to the list in the Maintainers.md file in DscResources repo (when doing new PR)
10. Should include the metadata tag 'DSCResourceKit' in the module manifest (when approved). Not sure about this one (@johlju, @PlagueHO ?)
11. It seems that Markdown lint [failed on AppVeyor](https://ci.appveyor.com/project/mgreenegit/UpdateServicesDsc/branch/dev#L1543) but should be skipped, will investigate
12. Seems to be a few PSSA rules complaining in `MSFT_UpdateServicesServer.psm1`,`MSFT_UpdateServicesCleanup.psm1` ('PSPossibleIncorrectComparisonWithNull' & Bracket style)
13. Missing Examples (but optional)
14. had a compilation error of your test when I ran it locally, will have a look
> "The property 'WorkingFolder' cannot be found on this object. Verify that the property exists." was thrown from C:\src\UpdateServicesDsc\Tests\Integration\UpdateServicesDsc.tests.ps1:28 char:13

As it's a new module that aims at being an HQRM, you could opt-in to more test (it would have caught 8).

**Comment by gaelcolas** [comment]
And your [DEV branch is way behind Master by 13 commits](https://github.com/mgreenegit/UpdateServicesDsc/compare/dev...master).
Work should be done on Dev and 'released' to master as per current workflow.

@rdbartram might help you out with the issues above? :)

**Comment by PlagueHO** [comment]
Awesome @mgreenegit and @gaelcolas - can't wait to get this one in!

Regards 9: From memory (@johlju might correct this) but we did agree that we'd add the DSCResourceKit tag for any community module that was listed here (and therefore met the HQRM standards).

**Comment by johlju** [comment]
The 'New resource module submission' issue template contains the below.

It just says tag 'DSCResource', but this is just a template, so we can add the tag 'DscResourceKit' as well. I think that would be good because that would mean it belongs to the "family" of the other modules.

The new resource module:

* [ ] is licensed under MIT.
* [ ] has the correct project structure.
* [ ] has a dev and master branch, and dev should default branch.
* [ ] is using DSC Resource Kit test templates.
* [ ] is connected to Codecov or similar.
* [ ] has established a code of conduct in ether a CODE_OF_CONDUCT.md or a
      'Code of conduct' section in the README.md.
* [ ] has either a CONTRIBUTING.md file or a 'Contributing' section in the
      README.md file.
* [ ] has included the metadata tag 'DSCResource' in the module manifest.
* [ ] is sufficiently [documented](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#writing-documentation).
* [ ] has an established [CI process](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#tests-in-appveyor) for each push to the repository.
* [ ] is sufficiently [tested](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#write-tests).
* [ ] Follows the guidelines set out for a
      [High Quality Resource Module](https://github.com/PowerShell/DscResources/blob/master/Naming.md#high-quality-resource-module).

**Comment by gaelcolas** [comment]
I fixed a bunch of other things in the open PR: mgreenegit/UpdateServicesDsc#33
You still need to address:
1, 3, 4, 6, 8, 12
1. New PR would be nice
3. Your default branch (configured in GH) is master, please change to Dev
4. You seem to have CodeCov only configured for the [master](https://codecov.io/gh/mgreenegit/UpdateServicesDsc/branch/master) branch (not [Dev](https://codecov.io/gh/mgreenegit/UpdateServicesDsc/branch/dev))
6. Integration test does not actually test if the values were set.
8. Add the repository to the list in the Maintainers.md file in DscResources repo (when doing new PR)
12. Missing Examples (but optional)

Adding another one:
17. It seems that your AppVeyor is not configured to build PRs (to Dev). So I can't test my PR builds successfully on AppVeyor

**Comment by gaelcolas** [comment]
The PR has been merged and the repo configured.
It is missing Integration Tests, but that probably should not be a blocker, as we can help improve the resource over time.
I think we're ready to include that one with the DSC Resource Kit.

@johlju & @PlagueHO: What do you think? Anything I'm missing?

**Comment by johlju** [comment]
You don’t think we should enforce having integration tests where possible? If not then we can allow other resources to be added without integration tests. If so we should update the module submission issue template (and documentation) that it is not necessary to be “HQRM”?

If so I’m okay with this.

**Comment by gaelcolas** [comment]
It's a balance of:
- ensuring continued quality and trust in the resource kit
- having easy to run Integration tests (see PowerShell/NetworkingDsc#379)
- giving a chance to newcomers, and support their growth in the community by being inclusive (not leaving them at the door for months)

I've put the thinking in #490 where we can have the generic discussion about how to make such choice. Then we can come back and make one for this specific case.

**Comment by gaelcolas** [comment]
FTR a new version has been released to the gallery, and I've implemented some integration tests using Test-Kitchen.
I'm now happy with the quality, although more integration tests could be written.
Given the changes going on, I'm going to put this one on hold and we'll revisit in a month or so.

**Comment by gaelcolas** [comment]
As announced during the last community call, we'd love to have this as part of [dsccommunity](https://github.com/dsccommunity). I'll work to transfer this one over along with the others.

**Comment by mgreenegit** [comment]
https://github.com/dsccommunity/UpdateServicesDsc

**Pull request closed without merging**
